kind: pipeline
name: release
steps:
    - name: build
      image: alpine
      commands:
          - apk add openjdk8-jre haxe curl neko
          - curl 'https://data.tilera.xyz/file/mpt/mpt-1.2-SNAPSHOT.jar' -o mpt.jar
          - haxelib setup /usr/share/haxe/lib
          - haxelib install kubejs

          - ./buildhaxe.sh
          - java -jar mpt.jar buildtwitch

          - mv build/notex-*-twitch.zip build/notex-twitch.zip

    - name: publish
      image: plugins/gitea-release
      settings:
          base_url: https://data.tilera.xyz/git
          api_key:
              from_secret: gitea_token
          note: CHANGELOG.md
          title: tag-${DRONE_TAG}
          files:
              - build/notex-twitch.zip
      when:
          event: tag
      depends_on:
          - build

